version: "3"
services:
  # strapi:
  #   container_name: strapi
  #   build:
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     DATABASE_CLIENT: postgres
  #     DATABASE_HOST: postgres
  #     DATABASE_PORT: 5432
  #     DATABASE_NAME: ${DATABASE_NAME}
  #     DATABASE_USERNAME: ${DATABASE_USERNAME}
  #     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  #     APP_KEYS: ${APP_KEYS}
  #     JWT_SECRET: ${JWT_SECRET}
  #     ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
  #     API_TOKEN_SALT: ${API_TOKEN_SALT}
  #     NODE_ENV: development
  #   volumes:
  #     - ./_docker_volumes/public/uploads:/opt/app/public/uploads
  #     - ./config:/opt/app/config
  #     - ./src:/opt/app/src
  #     - ./package.json:/opt/package.json
  #     - ./yarn.lock:/opt/yarn.lock
  #   ports:
  #     - "1337:1337"
  #   depends_on:
  #     - postgres

  postgres:
    container_name: postgres
    platform: linux/amd64 #for platform error on Apple M1 chips
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./_docker_volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
